SELECT 'This is SQL Exercise, Practice and Solution';
SELECT	1 AS one, 2 AS two, 3 AS trhee;
SELECT 10 + 15;
USE Scientists;
SHOW TABLES;
SELECT * FROM Scientists;
SELECT * FROM Projects;
SELECT CONCAT(Name, ' - ', Hours) AS 'Project/Hours' FROM Projects;
SELECT Name FROM Scientists ORDER BY Name;
SELECT Name FROM Projects ORDER BY Name DESC;
SELECT CONCAT('O prjeto ', Name, ' precisou de ', Hours, ' horas para ser concluído') AS Info FROM Projects;
SELECT CONCAT('O prjeto ', Name, ' precisou de ', Hours, ' horas para ser concluído') AS Info FROM Projects ORDER BY Name;
SELECT Name, Hours FROM Projects ORDER BY Hours DESC LIMIT 3; 
SELECT * FROM AssignedTo;
SELECT DISTINCT Project FROM AssignedTo;
SELECT Name, Hours FROM Projects ORDER BY Hours DESC LIMIT 1;
SELECT Name, Hours FROM Projects ORDER BY Hours ASC LIMIT 1 OFFSET 1;
SELECT * FROM Projects ORDER BY Hours ASC LIMIT 5;
SELECT CONCAT('Existem ', COUNT(Name) ,' cientistas na tabela Scientists') AS 'Number of Scientists' FROM Scientists ORDER BY Name;